site_name: basic_bot Docs
exclude_docs: |
  _archives/*

theme:
  name: material
  collapse_navigation: true
  sticky_navigation: false
  features:
    - search.highlight
    - navigation.path

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences